# Generated by Django 5.0.6 on 2025-01-21 14:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todoo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoo',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='todoo',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
